# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main

pool:
  name: default
 
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'

# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
#   inputs:
#     SourceFolder: src/Publish
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   enabled: false

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: src/Publish