# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main

pool:
  name: default
 
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: src/MVCFirst.sln
    feedsToUse: config
    nugetConfigPath: src/nuget.config

- task: VSBuild@1
  displayName: 'Build solution src/MVCFirst.sln'
  inputs:
    solution: src/MVCFirst.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
