# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main

pool:
  name: MVCProject Pipelines
  demands:
  - msbuild
  - visualstudio

variables:
  buildPlatform: 'any cpu'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: src/ProviderPortal.sln
    feedsToUse: config
    nugetConfigPath: src/nuget.config

- task: VSBuild@1
  displayName: 'Build solution src/ProviderPortal.sln'
  inputs:
    solution: src/ProviderPortal.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: src/Publish
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: src/Publish
