# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main

pool:
  name: default
   
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'   
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Unit Test Run'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
          echo $(Build.ArtifactStagingDirectory) + "Artific"
          echo $(System.DefaultWorkingDirectory) + "DefaultWorking"
          echo $(Agent.TempDirectory)  + "TempDirectory"
          echo $(buildPlatform) + "buildPlatform"
          echo $(buildConfiguration) + "buildConfiguration"

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '../src/Publish'
#     Contents: '**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#     OverWrite: true
#     preserveTimestamp: true
    
# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
