# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# trigger:
# - main

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build
      
      pool: 
        name: default
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        name: 'build_task'
        displayName: 'Build Solution & Publish'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile="$(System.DefaultWorkingDirectory)\\MVCFirst\Properties\PublishProfiles\FolderProfile.pubxml"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        displayName: Unit Test Execution
        name: 'unit_test_task' 
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)\MVCFirstTest\bin\Debug'
          
      - publish: '$(System.DefaultWorkingDirectory)\mypublishcopy'
        displayName: Publish build files
        artifact: buildartifcatfiles1

# - stage: deploy 
#   displayName: Deploy Stage
#   dependsOn: build
#   jobs:
#     - job: Deploy

#       pool: 
#         name: default

#       steps:
      
#       - download: current
#         artifact: buildartifcatfiles1
      
#       - task: CopyFiles@2
#         name: 'publish_task'
#         displayName: 'Copy Build to Release Dir'
#         inputs:
#           SourceFolder: '$(System.DefaultWorkingDirectory)\..\buildartifcatfiles1'
#           Contents: '**'
#           TargetFolder: '$(System.DefaultWorkingDirectory)\..\finalRelase'
#           OverWrite: true
#           preserveTimestamp: true